# This configuration files defines all projects scanned by
# the y2status tool.

jenkins:
  # Jenkins servers
  - label: External Jenkins - YaST
    url: https://ci.opensuse.org/view/Yast
  - label: External Jenkins - libyui
    url: https://ci.opensuse.org/view/libyui

  - label: Internal Jenkins - YaST
    url: https://ci.suse.de/view/YaST
    internal: true
  - label: Internal Jenkins - libyui
    url: https://ci.suse.de/view/libyui
    internal: true
  - label: Internal Jenkins - InstallTools
    url: https://ci.suse.de/view/InstallTools
    internal: true
  - label: Internal Jenkins - snapper
    # not included in any view, just a plain job
    url: https://ci.suse.de/job/snapper-master
    internal: true

obs:
  # OBS projects
  - project: YaST:Head

  - project: YaST:SLE-15:GA

  - project: YaST:SLE-12:SP4

  - project: YaST:SLE-12:SP3

  - project: filesystems:snapper

  - project: devel:libraries:libyui

  # TODO: system:install:head, but only the packages maintained
  # by the YaST team - e.g. linuxrc, i-i, hwinfo...

  # IBS projects
  - project: Devel:YaST:Head
    api: https://api.suse.de
    internal: true

  - project: Devel:YaST:CASP:4.0
    api: https://api.suse.de
    internal: true

  - project: Devel:YaST:SLE-15
    api: https://api.suse.de
    internal: true

  - project: Devel:YaST:SLE-12-SP4
    api: https://api.suse.de
    internal: true

  - project: Devel:YaST:SLE-12-SP3
    api: https://api.suse.de
    internal: true

docker:
  # Docker Hub images
  - yastdevel/ruby
  - yastdevel/cpp
  - yastdevel/libstorage-ng
  - libyui/devel
